// Regenerates src/abi.ts from `forge build` output. Run: forge build && npm run abi
import { readFileSync, writeFileSync } from 'node:fs'

const art = (name: string) => JSON.parse(readFileSync(`out/${name}.sol/${name}.json`, 'utf8'))
const v = art('AgentBudgetVault'), u = art('MockUSDC')
writeFileSync('src/abi.ts', `// GENERATED by scripts/gen-abi.ts from forge output. Do not edit.
export const vaultAbi = ${JSON.stringify(v.abi)} as const
export const vaultBytecode = '${v.bytecode.object}' as const
export const usdcAbi = ${JSON.stringify(u.abi)} as const
export const usdcBytecode = '${u.bytecode.object}' as const
`)
console.log('wrote src/abi.ts')
