// gen-abi.ts — write backend/abi.ts from `forge build` output ([IFACE]).
// The backend and auditor use the INTERFACE ABI (contracts/IAgentBudgetVault.sol), so an
// implementation change that breaks the interface fails to compile instead of drifting.
// Usage: npm run gen:abi   (then `git diff --exit-code backend/abi.ts` in CI / make check-iface)
import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';

const SOURCES = [
  { artifact: 'out/IAgentBudgetVault.sol/IAgentBudgetVault.json', name: 'vaultAbi', required: true },
  { artifact: 'out/MockUSDC.sol/MockUSDC.json', name: 'usdcAbi', required: false },
] as const;

let out =
  '// GENERATED by scripts/gen-abi.ts from forge build output. Do not edit by hand. [IFACE]\n' +
  '// Regenerate with: npm run gen:abi\n';

for (const s of SOURCES) {
  if (!existsSync(s.artifact)) {
    if (s.required) throw new Error(`missing ${s.artifact}; run forge build`);
    console.warn(`gen-abi: skip ${s.name} (${s.artifact} not built yet)`);
    continue;
  }
  const json = JSON.parse(await readFile(s.artifact, 'utf8')) as { abi: unknown[] };
  out += `\nexport const ${s.name} = ${JSON.stringify(json.abi, null, 2)} as const;\n`;
}

await writeFile('backend/abi.ts', out);
console.log('gen-abi: wrote backend/abi.ts');
